### ISSUE TITLE
dynamic tray icon

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/filecoin-station#166]
Assigned to @jopedroliveira for providing the asset, then to @bajtos for hooking it up 🙏 

<img width="116" alt="Screenshot 2022-09-27 at 16 29 47" src="https://user-images.githubusercontent.com/10247/192555736-44cdfa9d-ac44-4d98-9b98-6e0662f21ca0.png">

**Comment by jopedroliveira** [comment]
Other than the update icon, the on and off icons would be update as well. 
According to [this]( https://github.com/electron/electron/blob/main/docs/api/native-image.md#template-image), final these assets should be used as TemplateImages and proper filtering should be applied for the final appearance (light theme/dark theme), right?

**Comment by juliangruber** [comment]
> Other than the update icon, the on and off icons would be update as well.

Good point!



> According to [this](https://github.com/electron/electron/blob/main/docs/api/native-image.md#template-image), final these assets should be used as TemplateImages and proper filtering should be applied for the final appearance (light theme/dark theme), right?

This is only supported on macOS, so for a cross-platform solution we need that and regular images I think
