### ISSUE TITLE
L2-node CPU usage high

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/filecoin-station#198]
```bash
FIL_WALLET_ADDRESS=... ./build/saturn/l2node-darwin-x64/saturn-L2-node
```

low:
<img width="1081" alt="Screenshot 2022-09-30 at 13 47 08" src="https://user-images.githubusercontent.com/10247/193263183-007a51df-5ebe-4d06-a4d6-dd407077e82a.png">

high:
<img width="1076" alt="Screenshot 2022-09-30 at 13 48 17" src="https://user-images.githubusercontent.com/10247/193263208-068aa081-ba29-4f7f-bb9b-bbf51fcab134.png">

```bash
npm start
```

low:
<img width="1064" alt="Screenshot 2022-09-30 at 13 49 44" src="https://user-images.githubusercontent.com/10247/193263408-b01ae3a1-eb15-4d0d-9ebb-afe433d91f80.png">

high:
<img width="1071" alt="Screenshot 2022-09-30 at 13 49 33" src="https://user-images.githubusercontent.com/10247/193263429-f359cadd-ce0e-4bd6-af65-90da4a4e9bb3.png">

Why does it consume so much more CPU when spawned by electron? @bajtos do you have an idea?

**Comment by bajtos** [comment]
The Station is periodically calling L2's stats API over HTTP. IIRC, the current interval is 100ms.

https://github.com/filecoin-station/filecoin-station/blob/35ba8f72b6902019ebe0b84765bad799ef736350/main/saturn-node.js#L137-L140

Maybe this is contributing to CPU load?

**Comment by juliangruber** [comment]
Good catch! I'll try changing the interval.

Also potentially related: https://github.com/electron/electron/issues/31916

**Comment by juliangruber** [comment]
Indeed, this fixes the l2 load 😍  will PR

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/filecoin-station/pull/205
