### ISSUE TITLE
Sentry integration not working

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/filecoin-station#263]
Recent Station versions are not reporting to Sentry.

The release builds seem to have a -dev version number reported to the frontend.

```
> window.electron.stationBuildVersion
< '0.10.0.1-dev'
```

This problem was introduced by https://github.com/filecoin-station/filecoin-station/pull/183, but the root cause is in the way how we are constructing `stationBuildVersion` - maybe #138

**Comment by juliangruber** [comment]
I checked the `package.json` of a prod build, and found this at the end:

```
  "buildTag": null,
  "buildNumber": "1-dev"
```

**Comment by juliangruber** [comment]
```js
  if (!process.env.SENTRY_AUTH_TOKEN) {
    return {
      buildTag: null,
      buildNumber: '1-dev'
    }
  }
```

Looks like this condition falsely is true

**Comment by juliangruber** [comment]
Does this tell you anything, @bajtos?

**Comment by bajtos** [comment]
> I checked the `package.json` of a prod build, and found this at the end:
> 
> ```
>   "buildTag": null,
>   "buildNumber": "1-dev"
> ```

Yes, I was expecting this is the cause. The question is why are we getting no build tag?

https://github.com/filecoin-station/filecoin-station/blob/84ea5855c4fce52a17788c3276f558a59215dac8/.github/workflows/release.yml#L20-L22

https://github.com/filecoin-station/filecoin-station/blob/84ea5855c4fce52a17788c3276f558a59215dac8/build/configure-sentry.js#L9

https://github.com/filecoin-station/filecoin-station/blob/84ea5855c4fce52a17788c3276f558a59215dac8/build/before-pack.js#L18-L34

I think the problem is here:

https://github.com/filecoin-station/filecoin-station/blob/84ea5855c4fce52a17788c3276f558a59215dac8/build/before-pack.js#L19-L23

We are not setting `SENTRY_AUTH_TOKEN` inside `release.yml` workflow. Here is what we do for `ci.yml`:

https://github.com/filecoin-station/filecoin-station/blob/84ea5855c4fce52a17788c3276f558a59215dac8/.github/workflows/ci.yml#L62-L66

I think we should either:
- forward the env var as we do for the pull request (CI) builds, or 
- change `before-pack` to ignore `SENTRY_AUTH_TOKEN` when `GITHUB_REF_TYPE === 'tag'`

WDYT?

**Comment by juliangruber** [comment]
> * forward the env var as we do for the pull request (CI) builds, or

This is the cleaner solution to me, as it fixes the problem at the source, and makes the environments more consistent

**Comment by bajtos** [comment]
Nice, Station releases have the right build version now.

<img width="342" alt="Screenshot 2022-11-28 at 17 06 54" src="https://user-images.githubusercontent.com/1140553/204325494-bb8430c1-b399-4640-bfef-242cbe05e8bd.png">
