### ISSUE TITLE
my station node doesnt restart or update - I have to uninstall and redownload

### ISSUE THREAD

**Issue by momack2** [filecoin-station/filecoin-station#428]
I have tried multiple times to update station to the latest version - but I think your auto-updating (or manual updating) system is broken and/or versions are incompatible. this is pretty annoying for early users, and IMHO should be a top priority to bring folks along with new upgrades.

Ex, clicking the "restart now" button does nothing. manually rebooting the app also doesnt install the new version. I'd have to delete the app, install it, and sign up all over again, losing all my completed job progress

![CleanShot 2023-01-20 at 15 33 11](https://user-images.githubusercontent.com/618519/213738866-58498110-0b94-498b-be28-3664eaaaf67a.png)

**Comment by bajtos** [comment]
Hi @momack2, thank you for reporting this problem. We are aware of it - see https://github.com/filecoin-station/filecoin-station/issues/284.

As far as we understand this issue, it's a bug in the underlying Electron library we use for auto-updates, affecting only macOS Ventura users. See https://github.com/electron-userland/electron-builder/issues/7121

I agree that this is annoying and should be a top priority. Unfortunately, we don't have the expertise required :(

BTW, what's your experience with IPFS Desktop? Are you able to automatically update that app?

Let's continue the discussion in #284 please, to keep it in a single place.
