### ISSUE TITLE
"Restart Now" button doesn't install the new update of Station

### ISSUE THREAD

**Issue by davidd8** [filecoin-station/filecoin-station#471]
When starting Station, the top banner shows something like a "... new version of Station, restart to update" with a "Restart Now" button. When I press the button, Station restarts, but the banner still persists, so it doesn't update the version directly. 
<img width="931" alt="Screenshot 2023-02-08 at 1 30 26 PM" src="https://user-images.githubusercontent.com/390075/217661143-cfffbffb-528e-4827-87bf-84c60cdd666a.png">

Expected: Station updates from 0.9 to the latest version, 0.12
Actual: Station restarts but stays at v0.9

**Comment by bajtos** [comment]
Thank you, @davidd8 for reporting the issue to us. We are already aware of problems with the auto-update mechanism, see https://github.com/filecoin-station/filecoin-station/issues/284

Could you please leave a comment in https://github.com/filecoin-station/filecoin-station/issues/284 with the OS name and version you are using? E.g. "macOS Ventura" or "Windows 11".
