### ISSUE TITLE
ERR_NETWORK_IO_SUSPENDED

### ISSUE THREAD

**Issue by meandavejustice** [filecoin-station/filecoin-station#485]
![image](https://user-images.githubusercontent.com/1844554/218109736-769de38a-07a1-46d8-90a6-61a3318c9f1f.png)

Left laptop overnight, guessing this happened when closing lid. Would expect station to handle gracefully. Developer console was empty. Wish I had more info for you

**Comment by juliangruber** [comment]
This should be fixed in [0.13.2](https://github.com/filecoin-station/filecoin-station/releases/tag/v0.13.2) :v:
