### ISSUE TITLE
UI error monitoring

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/filecoin-station#78]
Setup error monitoring for Station UI.

- [x] Setup a new Sentry project (possibly using an existing PL account)
  → https://sentry.io/protocol-labs-ip/filecoin-station/ (not public)
- [x] Integrate Sentry into Station frontend
  → https://github.com/filecoin-project/filecoin-station/pull/138
- [x] Add a new paragraph to the Consent screen to describe what data is sent to Sentry. If the consent screen is not implemented yet, then add a new subtask to the appropriate issue.
  → https://github.com/filecoin-project/filecoin-station/pull/140
- [x] Report new releases to Sentry - see https://docs.sentry.io/product/releases/setup/release-automation/github-actions/
  → https://github.com/filecoin-project/filecoin-station/pull/163
- [x] Upload source maps to Sentry - see https://docs.sentry.io/platforms/javascript/sourcemaps/
  → https://github.com/filecoin-project/filecoin-station/pull/163
- [x] Disable Sentry integration for local development
  → https://github.com/filecoin-project/filecoin-station/pull/183
- [x] (should have) use `production` environment for builds created by GHA for git tags, `development` in all other cases.
  → done by the combination of #163 and #183 and #212
- [x] Consider integrating Sentry into Station backend too
  → https://github.com/filecoin-project/filecoin-station/pull/184

**Comment by juliangruber** [comment]
ping @patrickwoodhead

**Comment by patrickwoodhead** [comment]
@bajtos - I have create a Sentry team and sent you and @juliangruber an invitation

**Comment by bajtos** [comment]
> use `production` environment for builds created by GHA for git tags, development in all other cases

Here is my understanding of our current setup:

1. Inside `package.json`, both `buildTag` and `buildNumber` are set to null. As a result, CI tests running unpackaged code consider the version to be a dev one and disable Sentry integration. Developers running `npm start` and `npm test` locally fall into this category too.

2. When people download installers produced by our CI builds:

   - CI builds running for a git tag update `package.json` fields in the produced packages to report SENTRY RELEASE `x.y.z`. 
  
     One of our build steps configures Sentry with `environment=production` for this release.

   - Other CI builds triggered from our repository update `package.json` fields in the produced packages to report SENTRY RELEASE `x.y.z.{build-number}`. 
   
     One of our build steps configures Sentry with `environment=development` for this release. 

   - CI builds triggered for community-contributed pull requests update `package.json` fields in the produced packages to report SENTRY RELEASE `x.y.z.{build-number}`. 
   
     Because community-contributed PRs don't have access to secrets, these CI builds cannot create a Sentry release. As a result, errors for this version are considered to come from `production`. We need to fix this.
