### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/filecoin-station#79]
We want to collect metrics about the stations.

- [ ] Setup infra for collecting metrics (prior art: IPFS Desktop)
- Inside the Station, report the following metrics:
  - [ ] Number of jobs processed per hour
  - [ ] Number of stations up & running
     - Maybe we can report two data points - whether the station is running and whether Saturn L2 is connected to the network.
     - Do we want to report the Station version?
     - Do we want to report whether we are connected to Saturn test-net or main-net?
- [ ] Add a new paragraph to the Consent screen to describe what telemetry data is collected. If the consent screen is not implemented yet, then add a new subtask to the appropriate issue.
- [ ] Setup a simple dashboard to visualise collected data
- [ ] Create follow-up issues for anything left out of scope

Other metrics we can consider - but it's not clear whether users will be happy to share them and how much value we can actually get from them:
- Machine spec: CPU power, Memory size, Storage size
- Network speed test against an L1 node

**Comment by bajtos** [comment]
@bajtos or @juliangruber should take at prior art and decide what tooling & infra we want to use for this.

**Comment by juliangruber** [comment]
Depends on https://github.com/filecoin-project/filecoin-station/issues/80, as we can also use Plausible for event tracking

**Comment by bajtos** [comment]
IMO Plausible is not a good fit for this feature. In my understanding, Plausible is for web usage analytics, tracking various events related to how people navigate a website (or our Electron app).

The goal of this task (GH issue) is to implement a solution for collecting & visualising more detailed metrics, like number of jobs processed by each Station every minute. 

It's not clear to me how would you implement such metric using Plausible. Having said that, it's possible I am just not aware of advanced Plausible features that provide the functionality we need.

**Comment by juliangruber** [comment]
Thank you for checking this, I had assumed Plausible would be able to plot custom events well. This is also what IPFS Desktop does. If Plausible isn't a good fit, are we looking for a tool like prometheus then?

**Comment by bajtos** [comment]
> If Plausible isn't a good fit, are we looking for a tool like prometheus then?

Yes, I think we should take a look at Prometheus, Grafana, OpenTelemetry and similar tools.

**Comment by juliangruber** [comment]
https://www.influxdata.com/

**Comment by bajtos** [comment]
Maybe we can explore https://www.honeycomb.io too?

**Comment by bajtos** [comment]
How is Dat Desktop collecting telemetry?

Quoting from https://www.electronjs.org/blog/dat#what-are-some-challenges-youve-faced-while-building-dat-and-dat-desktop
> We also ran into some general Electron infrastructure problems, including:
> - Telemetry - how to capture anonymous usage statistics
> - Updates - It's kind of piecemeal and magic to set up automatic updates
> - Releases - XCode signing, building releases on Travis, doing beta builds, all were challenges.

**Comment by juliangruber** [comment]
> How is Dat Desktop collecting telemetry?

There is no telemetry in Dat Desktop yet, but I found an issue for it with some context: https://github.com/dat-ecosystem-archive/dat-desktop/issues/69

Dat Desktop was planned to mirror [WebTorrent](https://webtorrent.io/), to me it looks like that might have been using a custom telemetry implementation.

**Comment by bajtos** [comment]
Yeah. AFAICT, WebTorrent does indeed have a custom telemetry implementation.

Client: https://github.com/webtorrent/webtorrent-desktop/blob/e42a515199fedbe1aa1e79b8638ad1265f8cf50a/src/renderer/lib/telemetry.js

Server: https://github.com/webtorrent/webtorrent.io/blob/4af350fad04e842c48be5125d853d4ea2fdf9784/server/desktop-api.js

**Comment by juliangruber** [comment]
I'm in the process of setting up dashboards for Station in the PL Grafana, having everything under one hood will be very convenient and I think solidifies the requirement for some form of Grafana integration

**Comment by bajtos** [comment]
> I'm in the process of setting up dashboards for Station in the PL Grafana, having everything under one hood will be very convenient and I think solidifies the requirement for some form of Grafana integration

Awesome! I have assigned the issue to you then.

**Comment by bajtos** [comment]
> otherwise deploy Postgres to AWS and write a Lambda for submitting data

Based on my experience with setting up AWS RDS Aurora Postgres and AWS Lambda, I recommend to look for a solution requiring less infrastructure-related work.

- https://supabase.com offers hosted Postgres with REST & GraphQL API out of the box, plus serverless functions running on Deno Deploy

- https://www.cockroachlabs.com/, a cloud-native Postgres clone, has recently announced general availability of a Serverless offering with a generous free tier (5GiB Storage, 250M Request Units/month). They offer pg-client API only, we would have to operate the data-collection endpoint ourselves.

- https://planetscale.com is another contender in cloud-native database space. They are MySQL-compatible and offer serverless mode. They don't offer HTTP-based API, but provide serverless driver as an alternative to MySQL clients. See https://planetscale.com/docs/tutorials/planetscale-serverless-driver

Considering our needs, I think Supabase is the best option if we use InfluxDB.

**Comment by juliangruber** [comment]
> I think Supabase is the best option if we use InfluxDB.

If we _don't_ use InfluxDB, right?

**Comment by bajtos** [comment]
> > I think Supabase is the best option if we use InfluxDB.
> 
> If we _don't_ use InfluxDB, right?

Yes, sorry for the typo. I'll edit my comment.

**Comment by juliangruber** [comment]
Ok, agreed on all points then :)
